---
name: pyesgf-cmip6
channels:
  - conda-forge
  - nodefaults

dependencies:
  # installation
  - python=3.11
  - pip
  - esgf-pyclient
  - pandas
  - netcdf4
  - xarray
  - dask
  - python-cdo
  - matplotlib
  - joblib
  - tqdm
  - notebook
  - cartopy
